name: Setup cargo-rbmt
description: Install cargo-rbmt from crates.io

runs:
    using: "composite"

    steps:
        - name: Install cargo-rbmt
          shell: bash
          run: |
              RBMT_VERSION=$(grep -A 1 '^\[package\.metadata\.rbmt\]$' Cargo.toml | grep -E -o '[0-9]+([.][0-9]+)*')
              echo "Installing cargo-rbmt@v${RBMT_VERSION} from crates.io"
              cargo install cargo-rbmt --version "$RBMT_VERSION" --locked

        - name: Install Rust Toolchains
          shell: bash
          run: cargo rbmt toolchains

        - name: Install cargo-rbmt Tools
          shell: bash
          run: cargo rbmt tools
