name: Rust CI

on:
    push:
    pull_request:

permissions: {}
env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1

jobs:
    check:
        name: Check - ${{ matrix.name }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Documentation
                      task: docs
                    - name: Formatting
                      task: fmt --check
                    - name: Linting
                      task: lint

        steps:
            - name: Checkout Repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Setup Build Cache
              uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

            - name: Setup cargo-rbmt
              uses: ./.github/actions/setup-rbmt

            - name: ${{ matrix.name }}
              run: cargo rbmt ${{ matrix.task }}

    test:
        name: Test - ${{ matrix.name }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Stable Toolchain + Recent Lockfile
                      toolchain: stable
                      lockfile: recent
                    - name: MSRV Toolchain + Minimal Lockfile
                      toolchain: msrv
                      lockfile: minimal

        steps:
            - name: Checkout Repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Setup Build Cache
              uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

            - name: Setup cargo-rbmt
              uses: ./.github/actions/setup-rbmt

            - name: ${{ matrix.name }}
              run: cargo rbmt test --toolchain ${{ matrix.toolchain }} --lockfile ${{ matrix.lockfile }}
