name: Rust CI

on: [push, pull_request]

permissions: {}
env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1

jobs:
    check:
        name: Check - ${{ matrix.name }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Check Formatting
                      task: fmt --check
                    - name: Lint
                      task: lint
                    - name: Documentation
                      task: docs

        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Setup build cache
              uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

            - name: Setup cargo-rbmt
              uses: ./.github/actions/setup-rbmt

            - name: Run ${{ matrix.task }}
              run: cargo rbmt ${{ matrix.task }}

    test:
        name: Test - ${{ matrix.toolchain }} toolchain, ${{ matrix.lockfile }} deps
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - toolchain: stable
                      lockfile: recent
                    - toolchain: msrv
                      lockfile: minimal
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Setup build cache
              uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

            - name: Setup cargo-rbmt
              uses: ./.github/actions/setup-rbmt

            - name: Run tests
              run: cargo rbmt test --toolchain ${{ matrix.toolchain }} --lock-file ${{ matrix.lockfile }}
